### ISSUE TITLE
Old Brawl Not Working

### ISSUE THREAD

**Issue by Kevinjky7555** [VitalikObject/OldBrawl#1]
The Old Brawl APK doesn't work at all. Even if I run 'main.py' it still doesn't work. It keeps saying: Unable to connect with the server. Check your internet connection and try again.

Please fix.

**Comment by Kevinjky7555** [comment]
Also even if I run 'setup.py' too*

**Comment by XeonDevv** [comment]
edit frida gadget config

**Comment by Kevinjky7555** [comment]
Uhh, what do I edit in it?

**Comment by SB-Deco** [comment]
change the ip from whatever it is to 127.0.0.1

**Comment by VitalikObject** [comment]
a working!
