### ISSUE TITLE
Client not working

### ISSUE THREAD

**Issue by AdeeGaming01** [VitalikObject/OldBrawl#2]
After downloading v12 server and client then modifying libmrvitalik.config.so, it connects to SC's server. I tried both on BlueStacks and on my phone and it always says Update available. And in the server console it doesn't say New connection 127.x.x. Please help

**Comment by VitalikObject** [comment]
Hi! Which ip address do you use in config. Seems this ip doesn't exist and game cannot connect to it.

**Comment by AdeeGaming01** [comment]
It seems that I typed it in wrong, but I'll check
