### ISSUE TITLE
After the client connects to the server, an error occurs.

### ISSUE THREAD

**Issue by xmopser** [VitalikObject/OldBrawl#3]
When the client connects to the server, it doesn't connect. And writes this in the server console. What should I do?
![Screenshot_544](https://user-images.githubusercontent.com/78369368/107923803-0fb74500-6f83-11eb-8f2b-dff6c22cccbc.png)

**Comment by VitalikObject** [comment]
Which client do you use?

**Comment by VitalikObject** [comment]
а спасибо за комментарий!
