### ISSUE TITLE
module _tweetnacl

### ISSUE THREAD

**Issue by MistiDev** [VitalikObject/OldBrawl#7]
Is there any way to install the "_tweetnacl" module on androyd using Pydroid 3?

**Comment by ariportrait** [comment]
yes, by going on "terminal"

**Comment by SB-Deco** [comment]
I tried in terminal but didn't work

**Comment by ariportrait** [comment]
u have to do in terminal
cd Download
cd OldBrawl-main
cd Server
cd TweetNacl
python setup.py install

if i'm not wrong this should be the progress, in case its not, then i'll
send you a tutorial video

Il giorno mer 9 giu 2021 alle ore 23:00 SB-Deco ***@***.***>
ha scritto:
